### ISSUE TITLE
LDAPAdmin: order of ssh keys in SN does not match displayed key order

### ISSUE THREAD

**Issue by wutz10** [denkunddachte-agaffke/B2BiUtils#17]
User was created adding 2 keys at once - -L -v shows key indexes do not match SN comments

**Comment by agaffke-az** [comment]
Also: when manipulating keys (adding/removing), SN should be modified to reflect the changes.

**Comment by denkunddachte-agaffke** [comment]
Fixed in API. LDAPUser.getSshPublicKeys() and LDAPUser.getObjectClasses() return Collection with items in their original order.
