### ISSUE TITLE
LDAPAdmin: make key operations atomic

### ISSUE THREAD

**Issue by agaffke-az** [denkunddachte-agaffke/B2BiUtils#20]
Currently, --deleteAllKeys --addKey key... will remove keys, save object then add key(s) and save again.

**Comment by denkunddachte-agaffke** [comment]
All key operations are now all done on the cached object before updating on server. Any combination of --deleteAllKeys or --deleteKeysExcept or --deleteKey and --addKey can be used, where delete operation are mutually exclusive and are processed in the indicated order.
