### ISSUE TITLE
WorkflowMgr: implement local prefix handler

### ISSUE THREAD

**Issue by denkunddachte-agaffke** [denkunddachte-agaffke/B2BiUtils#31]
When uploading / downloading artifacts (WFDs, XSLTs?)

1. rename artifacts  changing local prefix "DD_" to configurable site prefix
2. rename adapter/services in the same manner

**Comment by agaffke-az** [comment]
Especially for DD_API_WS: enable mapping of "default" services/adapters in DD_API_WS.bpml to locally available ones...

**Comment by denkunddachte-agaffke** [comment]
Implemented service/adapter mapping for DD_API_WS update.
For now, I cannot see a use case for a general site prefix mapping, so I'll de-scope this (as it's implementation is elaborate...)
