### ISSUE TITLE
WFMgr: creation of new XSLT fails 

### ISSUE THREAD

**Issue by agaffke-az** [denkunddachte-agaffke/B2BiUtils#33]
Trying to initially create a new XSLT via DD_API_WS->Import Service results in error:

Status report on 2023-08-08 09:41:44.571 for service: Import
XSLT Template :: AZ_REPORT_PGP_KEY_EXPIRY :: load :: Message :: No Update. Record currently exists
End of report

Same error occurs when trying to import generated XML via dashboard...

**Comment by agaffke-az** [comment]
Update existing XSLT works.

**Comment by denkunddachte-agaffke** [comment]
Fixed
