### ISSUE TITLE
WFDUtil: Workflows API getting wrong versions

### ISSUE THREAD

**Issue by agaffke-az** [denkunddachte-agaffke/B2BiUtils#43]
https://xxx/B2BAPIs/svc/workflows/AZ_SB_PROCESS_AV does not always get default version :-(
https://xxx/B2BAPIs/svc/workflows/?_range=0-999&fieldList=&searchFor=AZ_SB_PROCESS_AV does ...

refreshWFD does not help :-(

**Comment by denkunddachte-agaffke** [comment]
Use searchFor=... lookup to get default version (this should usually work... but the workflows API is buggy)
